version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: qs
    versions:
    - 6.10.0
    - 6.9.6
  - dependency-name: react-popper
    versions:
    - 1.3.10
    - 1.3.7
    - 1.3.8
    - 1.3.9
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: react-icons
    versions:
    - 4.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: redux
    versions:
    - 4.0.5
