// flow-typed signature: 4477a086cd9e70e6d8cec47df53fd53c
// flow-typed version: <<STUB>>/bootswatch_v^3.3.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootswatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootswatch' {
  declare module.exports: any;
}
