// flow-typed signature: bd6fad2d1d675450da7e08aa0e097ab4
// flow-typed version: <<STUB>>/chart.js_v2.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chart.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chart.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chart.js/dist/Chart.bundle' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart.bundle.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart.min' {
  declare module.exports: any;
}

declare module 'chart.js/gulpfile' {
  declare module.exports: any;
}

declare module 'chart.js/karma.conf.ci' {
  declare module.exports: any;
}

declare module 'chart.js/karma.conf' {
  declare module.exports: any;
}

declare module 'chart.js/karma.coverage.conf' {
  declare module.exports: any;
}

declare module 'chart.js/samples/utils' {
  declare module.exports: any;
}

declare module 'chart.js/src/chart' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Bar' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Bubble' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Doughnut' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Line' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.PolarArea' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Radar' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Scatter' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.bar' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.bubble' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.doughnut' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.line' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.polarArea' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.radar' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.animation' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.canvasHelpers' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.controller' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.datasetController' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.element' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.helpers' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.interaction' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.layoutService' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.legend' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.plugin' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.scale' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.scaleService' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.ticks' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.title' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.tooltip' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.arc' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.line' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.point' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.rectangle' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.category' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.linear' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.linearbase' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.logarithmic' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.radialLinear' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.time' {
  declare module.exports: any;
}

declare module 'chart.js/test/controller.bar.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/controller.bubble.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/controller.doughnut.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/controller.line.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/controller.polarArea.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/controller.radar.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.controller.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.datasetController.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.element.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.helpers.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.interaction.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.layoutService.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.legend.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.plugin.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.scaleService.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.title.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/core.tooltip.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/defaultConfig.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/element.arc.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/element.line.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/element.point.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/element.rectangle.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/mockContext' {
  declare module.exports: any;
}

declare module 'chart.js/test/scale.category.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/scale.linear.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/scale.logarithmic.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/scale.radialLinear.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/scale.time.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chart.js/dist/Chart.bundle.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.bundle'>;
}
declare module 'chart.js/dist/Chart.bundle.min.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.bundle.min'>;
}
declare module 'chart.js/dist/Chart.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart'>;
}
declare module 'chart.js/dist/Chart.min.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.min'>;
}
declare module 'chart.js/gulpfile.js' {
  declare module.exports: $Exports<'chart.js/gulpfile'>;
}
declare module 'chart.js/karma.conf.ci.js' {
  declare module.exports: $Exports<'chart.js/karma.conf.ci'>;
}
declare module 'chart.js/karma.conf.js' {
  declare module.exports: $Exports<'chart.js/karma.conf'>;
}
declare module 'chart.js/karma.coverage.conf.js' {
  declare module.exports: $Exports<'chart.js/karma.coverage.conf'>;
}
declare module 'chart.js/samples/utils.js' {
  declare module.exports: $Exports<'chart.js/samples/utils'>;
}
declare module 'chart.js/src/chart.js' {
  declare module.exports: $Exports<'chart.js/src/chart'>;
}
declare module 'chart.js/src/charts/Chart.Bar.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Bar'>;
}
declare module 'chart.js/src/charts/Chart.Bubble.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Bubble'>;
}
declare module 'chart.js/src/charts/Chart.Doughnut.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Doughnut'>;
}
declare module 'chart.js/src/charts/Chart.Line.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Line'>;
}
declare module 'chart.js/src/charts/Chart.PolarArea.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.PolarArea'>;
}
declare module 'chart.js/src/charts/Chart.Radar.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Radar'>;
}
declare module 'chart.js/src/charts/Chart.Scatter.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Scatter'>;
}
declare module 'chart.js/src/controllers/controller.bar.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.bar'>;
}
declare module 'chart.js/src/controllers/controller.bubble.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.bubble'>;
}
declare module 'chart.js/src/controllers/controller.doughnut.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.doughnut'>;
}
declare module 'chart.js/src/controllers/controller.line.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.line'>;
}
declare module 'chart.js/src/controllers/controller.polarArea.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.polarArea'>;
}
declare module 'chart.js/src/controllers/controller.radar.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.radar'>;
}
declare module 'chart.js/src/core/core.animation.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.animation'>;
}
declare module 'chart.js/src/core/core.canvasHelpers.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.canvasHelpers'>;
}
declare module 'chart.js/src/core/core.controller.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.controller'>;
}
declare module 'chart.js/src/core/core.datasetController.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.datasetController'>;
}
declare module 'chart.js/src/core/core.element.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.element'>;
}
declare module 'chart.js/src/core/core.helpers.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.helpers'>;
}
declare module 'chart.js/src/core/core.interaction.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.interaction'>;
}
declare module 'chart.js/src/core/core.js' {
  declare module.exports: $Exports<'chart.js/src/core/core'>;
}
declare module 'chart.js/src/core/core.layoutService.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.layoutService'>;
}
declare module 'chart.js/src/core/core.legend.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.legend'>;
}
declare module 'chart.js/src/core/core.plugin.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.plugin'>;
}
declare module 'chart.js/src/core/core.scale.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.scale'>;
}
declare module 'chart.js/src/core/core.scaleService.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.scaleService'>;
}
declare module 'chart.js/src/core/core.ticks.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.ticks'>;
}
declare module 'chart.js/src/core/core.title.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.title'>;
}
declare module 'chart.js/src/core/core.tooltip.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.tooltip'>;
}
declare module 'chart.js/src/elements/element.arc.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.arc'>;
}
declare module 'chart.js/src/elements/element.line.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.line'>;
}
declare module 'chart.js/src/elements/element.point.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.point'>;
}
declare module 'chart.js/src/elements/element.rectangle.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.rectangle'>;
}
declare module 'chart.js/src/scales/scale.category.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.category'>;
}
declare module 'chart.js/src/scales/scale.linear.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.linear'>;
}
declare module 'chart.js/src/scales/scale.linearbase.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.linearbase'>;
}
declare module 'chart.js/src/scales/scale.logarithmic.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.logarithmic'>;
}
declare module 'chart.js/src/scales/scale.radialLinear.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.radialLinear'>;
}
declare module 'chart.js/src/scales/scale.time.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.time'>;
}
declare module 'chart.js/test/controller.bar.tests.js' {
  declare module.exports: $Exports<'chart.js/test/controller.bar.tests'>;
}
declare module 'chart.js/test/controller.bubble.tests.js' {
  declare module.exports: $Exports<'chart.js/test/controller.bubble.tests'>;
}
declare module 'chart.js/test/controller.doughnut.tests.js' {
  declare module.exports: $Exports<'chart.js/test/controller.doughnut.tests'>;
}
declare module 'chart.js/test/controller.line.tests.js' {
  declare module.exports: $Exports<'chart.js/test/controller.line.tests'>;
}
declare module 'chart.js/test/controller.polarArea.tests.js' {
  declare module.exports: $Exports<'chart.js/test/controller.polarArea.tests'>;
}
declare module 'chart.js/test/controller.radar.tests.js' {
  declare module.exports: $Exports<'chart.js/test/controller.radar.tests'>;
}
declare module 'chart.js/test/core.controller.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.controller.tests'>;
}
declare module 'chart.js/test/core.datasetController.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.datasetController.tests'>;
}
declare module 'chart.js/test/core.element.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.element.tests'>;
}
declare module 'chart.js/test/core.helpers.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.helpers.tests'>;
}
declare module 'chart.js/test/core.interaction.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.interaction.tests'>;
}
declare module 'chart.js/test/core.layoutService.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.layoutService.tests'>;
}
declare module 'chart.js/test/core.legend.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.legend.tests'>;
}
declare module 'chart.js/test/core.plugin.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.plugin.tests'>;
}
declare module 'chart.js/test/core.scaleService.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.scaleService.tests'>;
}
declare module 'chart.js/test/core.title.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.title.tests'>;
}
declare module 'chart.js/test/core.tooltip.tests.js' {
  declare module.exports: $Exports<'chart.js/test/core.tooltip.tests'>;
}
declare module 'chart.js/test/defaultConfig.tests.js' {
  declare module.exports: $Exports<'chart.js/test/defaultConfig.tests'>;
}
declare module 'chart.js/test/element.arc.tests.js' {
  declare module.exports: $Exports<'chart.js/test/element.arc.tests'>;
}
declare module 'chart.js/test/element.line.tests.js' {
  declare module.exports: $Exports<'chart.js/test/element.line.tests'>;
}
declare module 'chart.js/test/element.point.tests.js' {
  declare module.exports: $Exports<'chart.js/test/element.point.tests'>;
}
declare module 'chart.js/test/element.rectangle.tests.js' {
  declare module.exports: $Exports<'chart.js/test/element.rectangle.tests'>;
}
declare module 'chart.js/test/mockContext.js' {
  declare module.exports: $Exports<'chart.js/test/mockContext'>;
}
declare module 'chart.js/test/scale.category.tests.js' {
  declare module.exports: $Exports<'chart.js/test/scale.category.tests'>;
}
declare module 'chart.js/test/scale.linear.tests.js' {
  declare module.exports: $Exports<'chart.js/test/scale.linear.tests'>;
}
declare module 'chart.js/test/scale.logarithmic.tests.js' {
  declare module.exports: $Exports<'chart.js/test/scale.logarithmic.tests'>;
}
declare module 'chart.js/test/scale.radialLinear.tests.js' {
  declare module.exports: $Exports<'chart.js/test/scale.radialLinear.tests'>;
}
declare module 'chart.js/test/scale.time.tests.js' {
  declare module.exports: $Exports<'chart.js/test/scale.time.tests'>;
}
