// flow-typed signature: aec3bf226148457ae799872a12f815fc
// flow-typed version: <<STUB>>/extract-loader_v^0.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-loader/lib/extractLoader' {
  declare module.exports: any;
}

declare module 'extract-loader/src/extractLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-loader/lib/extractLoader.js' {
  declare module.exports: $Exports<'extract-loader/lib/extractLoader'>;
}
declare module 'extract-loader/src/extractLoader.js' {
  declare module.exports: $Exports<'extract-loader/src/extractLoader'>;
}
