// flow-typed signature: 8e321c16cf4f4f8fe5beb76101203a83
// flow-typed version: <<STUB>>/html-minify-loader_v^1.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-minify-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-minify-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-minify-loader/index' {
  declare module.exports: $Exports<'html-minify-loader'>;
}
declare module 'html-minify-loader/index.js' {
  declare module.exports: $Exports<'html-minify-loader'>;
}
