// flow-typed signature: de62056e3b6ecff622c7b8c7faa715aa
// flow-typed version: <<STUB>>/immutability-helper_v^2.1.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutability-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutability-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'immutability-helper/index' {
  declare module.exports: $Exports<'immutability-helper'>;
}
declare module 'immutability-helper/index.js' {
  declare module.exports: $Exports<'immutability-helper'>;
}
