// flow-typed signature: bf556589be2cb2546d9c5fcde3649a14
// flow-typed version: <<STUB>>/node-deb_v^0.9.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-deb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-deb' {
  declare module.exports: any;
}
