// flow-typed signature: c41f6de6af80045efd33a414852e7c7b
// flow-typed version: <<STUB>>/node-puppetdbquery_v^1.1.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-puppetdbquery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-puppetdbquery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-puppetdbquery/cli' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/lib/ast' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/lib/evaluator' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/lib/main' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/lib/util' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/main' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/test/main_test' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/test/parser_test' {
  declare module.exports: any;
}

declare module 'node-puppetdbquery/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-puppetdbquery/cli.js' {
  declare module.exports: $Exports<'node-puppetdbquery/cli'>;
}
declare module 'node-puppetdbquery/lib/ast.js' {
  declare module.exports: $Exports<'node-puppetdbquery/lib/ast'>;
}
declare module 'node-puppetdbquery/lib/evaluator.js' {
  declare module.exports: $Exports<'node-puppetdbquery/lib/evaluator'>;
}
declare module 'node-puppetdbquery/lib/main.js' {
  declare module.exports: $Exports<'node-puppetdbquery/lib/main'>;
}
declare module 'node-puppetdbquery/lib/util.js' {
  declare module.exports: $Exports<'node-puppetdbquery/lib/util'>;
}
declare module 'node-puppetdbquery/main.js' {
  declare module.exports: $Exports<'node-puppetdbquery/main'>;
}
declare module 'node-puppetdbquery/test/main_test.js' {
  declare module.exports: $Exports<'node-puppetdbquery/test/main_test'>;
}
declare module 'node-puppetdbquery/test/parser_test.js' {
  declare module.exports: $Exports<'node-puppetdbquery/test/parser_test'>;
}
declare module 'node-puppetdbquery/webpack.config.js' {
  declare module.exports: $Exports<'node-puppetdbquery/webpack.config'>;
}
