// flow-typed signature: 87211792177acfa9beb9150d02dfda11
// flow-typed version: <<STUB>>/object-dig_v^0.1.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-dig'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-dig' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-dig/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-dig/dist/index.js' {
  declare module.exports: $Exports<'object-dig/dist/index'>;
}
