// flow-typed signature: 1dd033aa1ecd3d7bdd313ee534ac4e2b
// flow-typed version: <<STUB>>/object-hash_v^1.1.8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-hash/dist/object_hash_test' {
  declare module.exports: any;
}

declare module 'object-hash/dist/object_hash' {
  declare module.exports: any;
}

declare module 'object-hash/gulpfile' {
  declare module.exports: any;
}

declare module 'object-hash/karma.conf' {
  declare module.exports: any;
}

declare module 'object-hash/test/blob' {
  declare module.exports: any;
}

declare module 'object-hash/test/index' {
  declare module.exports: any;
}

declare module 'object-hash/test/object-classes' {
  declare module.exports: any;
}

declare module 'object-hash/test/old-crypto' {
  declare module.exports: any;
}

declare module 'object-hash/test/replacer' {
  declare module.exports: any;
}

declare module 'object-hash/test/types' {
  declare module.exports: any;
}

declare module 'object-hash/test/writeToStream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-hash/dist/object_hash_test.js' {
  declare module.exports: $Exports<'object-hash/dist/object_hash_test'>;
}
declare module 'object-hash/dist/object_hash.js' {
  declare module.exports: $Exports<'object-hash/dist/object_hash'>;
}
declare module 'object-hash/gulpfile.js' {
  declare module.exports: $Exports<'object-hash/gulpfile'>;
}
declare module 'object-hash/index' {
  declare module.exports: $Exports<'object-hash'>;
}
declare module 'object-hash/index.js' {
  declare module.exports: $Exports<'object-hash'>;
}
declare module 'object-hash/karma.conf.js' {
  declare module.exports: $Exports<'object-hash/karma.conf'>;
}
declare module 'object-hash/test/blob.js' {
  declare module.exports: $Exports<'object-hash/test/blob'>;
}
declare module 'object-hash/test/index.js' {
  declare module.exports: $Exports<'object-hash/test/index'>;
}
declare module 'object-hash/test/object-classes.js' {
  declare module.exports: $Exports<'object-hash/test/object-classes'>;
}
declare module 'object-hash/test/old-crypto.js' {
  declare module.exports: $Exports<'object-hash/test/old-crypto'>;
}
declare module 'object-hash/test/replacer.js' {
  declare module.exports: $Exports<'object-hash/test/replacer'>;
}
declare module 'object-hash/test/types.js' {
  declare module.exports: $Exports<'object-hash/test/types'>;
}
declare module 'object-hash/test/writeToStream.js' {
  declare module.exports: $Exports<'object-hash/test/writeToStream'>;
}
