// flow-typed signature: 21d74e5bebe37843e2895d9e67ec61e9
// flow-typed version: <<STUB>>/protractor_v^5.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'protractor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'protractor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'protractor/bin/elementexplorer' {
  declare module.exports: any;
}

declare module 'protractor/built/bpRunner' {
  declare module.exports: any;
}

declare module 'protractor/built/breakpointhook' {
  declare module.exports: any;
}

declare module 'protractor/built/browser' {
  declare module.exports: any;
}

declare module 'protractor/built/cli' {
  declare module.exports: any;
}

declare module 'protractor/built/clientsidescripts' {
  declare module.exports: any;
}

declare module 'protractor/built/config' {
  declare module.exports: any;
}

declare module 'protractor/built/configParser' {
  declare module.exports: any;
}

declare module 'protractor/built/debugger' {
  declare module.exports: any;
}

declare module 'protractor/built/debugger/clients/explorer' {
  declare module.exports: any;
}

declare module 'protractor/built/debugger/clients/wddebugger' {
  declare module.exports: any;
}

declare module 'protractor/built/debugger/debuggerCommons' {
  declare module.exports: any;
}

declare module 'protractor/built/debugger/modes/commandRepl' {
  declare module.exports: any;
}

declare module 'protractor/built/debugger/modes/debuggerRepl' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/attachSession' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/browserStack' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/direct' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/driverProvider' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/hosted' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/index' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/local' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/mock' {
  declare module.exports: any;
}

declare module 'protractor/built/driverProviders/sauce' {
  declare module.exports: any;
}

declare module 'protractor/built/element' {
  declare module.exports: any;
}

declare module 'protractor/built/exitCodes' {
  declare module.exports: any;
}

declare module 'protractor/built/expectedConditions' {
  declare module.exports: any;
}

declare module 'protractor/built/frameworks/__protractor_internal_afterEach_setup_spec' {
  declare module.exports: any;
}

declare module 'protractor/built/frameworks/debugprint' {
  declare module.exports: any;
}

declare module 'protractor/built/frameworks/explorer' {
  declare module.exports: any;
}

declare module 'protractor/built/frameworks/jasmine' {
  declare module.exports: any;
}

declare module 'protractor/built/frameworks/mocha' {
  declare module.exports: any;
}

declare module 'protractor/built/frameworks/setupAfterEach' {
  declare module.exports: any;
}

declare module 'protractor/built/index' {
  declare module.exports: any;
}

declare module 'protractor/built/launcher' {
  declare module.exports: any;
}

declare module 'protractor/built/locators' {
  declare module.exports: any;
}

declare module 'protractor/built/logger' {
  declare module.exports: any;
}

declare module 'protractor/built/plugins' {
  declare module.exports: any;
}

declare module 'protractor/built/ptor' {
  declare module.exports: any;
}

declare module 'protractor/built/runner' {
  declare module.exports: any;
}

declare module 'protractor/built/runnerCli' {
  declare module.exports: any;
}

declare module 'protractor/built/selenium-webdriver/locators' {
  declare module.exports: any;
}

declare module 'protractor/built/selenium-webdriver/webdriver' {
  declare module.exports: any;
}

declare module 'protractor/built/taskLogger' {
  declare module.exports: any;
}

declare module 'protractor/built/taskRunner' {
  declare module.exports: any;
}

declare module 'protractor/built/taskScheduler' {
  declare module.exports: any;
}

declare module 'protractor/built/util' {
  declare module.exports: any;
}

declare module 'protractor/built/webdriver-js-extender/index' {
  declare module.exports: any;
}

declare module 'protractor/example/conf' {
  declare module.exports: any;
}

declare module 'protractor/example/example_spec' {
  declare module.exports: any;
}

declare module 'protractor/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'protractor/bin/elementexplorer.js' {
  declare module.exports: $Exports<'protractor/bin/elementexplorer'>;
}
declare module 'protractor/built/bpRunner.js' {
  declare module.exports: $Exports<'protractor/built/bpRunner'>;
}
declare module 'protractor/built/breakpointhook.js' {
  declare module.exports: $Exports<'protractor/built/breakpointhook'>;
}
declare module 'protractor/built/browser.js' {
  declare module.exports: $Exports<'protractor/built/browser'>;
}
declare module 'protractor/built/cli.js' {
  declare module.exports: $Exports<'protractor/built/cli'>;
}
declare module 'protractor/built/clientsidescripts.js' {
  declare module.exports: $Exports<'protractor/built/clientsidescripts'>;
}
declare module 'protractor/built/config.js' {
  declare module.exports: $Exports<'protractor/built/config'>;
}
declare module 'protractor/built/configParser.js' {
  declare module.exports: $Exports<'protractor/built/configParser'>;
}
declare module 'protractor/built/debugger.js' {
  declare module.exports: $Exports<'protractor/built/debugger'>;
}
declare module 'protractor/built/debugger/clients/explorer.js' {
  declare module.exports: $Exports<'protractor/built/debugger/clients/explorer'>;
}
declare module 'protractor/built/debugger/clients/wddebugger.js' {
  declare module.exports: $Exports<'protractor/built/debugger/clients/wddebugger'>;
}
declare module 'protractor/built/debugger/debuggerCommons.js' {
  declare module.exports: $Exports<'protractor/built/debugger/debuggerCommons'>;
}
declare module 'protractor/built/debugger/modes/commandRepl.js' {
  declare module.exports: $Exports<'protractor/built/debugger/modes/commandRepl'>;
}
declare module 'protractor/built/debugger/modes/debuggerRepl.js' {
  declare module.exports: $Exports<'protractor/built/debugger/modes/debuggerRepl'>;
}
declare module 'protractor/built/driverProviders/attachSession.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/attachSession'>;
}
declare module 'protractor/built/driverProviders/browserStack.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/browserStack'>;
}
declare module 'protractor/built/driverProviders/direct.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/direct'>;
}
declare module 'protractor/built/driverProviders/driverProvider.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/driverProvider'>;
}
declare module 'protractor/built/driverProviders/hosted.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/hosted'>;
}
declare module 'protractor/built/driverProviders/index.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/index'>;
}
declare module 'protractor/built/driverProviders/local.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/local'>;
}
declare module 'protractor/built/driverProviders/mock.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/mock'>;
}
declare module 'protractor/built/driverProviders/sauce.js' {
  declare module.exports: $Exports<'protractor/built/driverProviders/sauce'>;
}
declare module 'protractor/built/element.js' {
  declare module.exports: $Exports<'protractor/built/element'>;
}
declare module 'protractor/built/exitCodes.js' {
  declare module.exports: $Exports<'protractor/built/exitCodes'>;
}
declare module 'protractor/built/expectedConditions.js' {
  declare module.exports: $Exports<'protractor/built/expectedConditions'>;
}
declare module 'protractor/built/frameworks/__protractor_internal_afterEach_setup_spec.js' {
  declare module.exports: $Exports<'protractor/built/frameworks/__protractor_internal_afterEach_setup_spec'>;
}
declare module 'protractor/built/frameworks/debugprint.js' {
  declare module.exports: $Exports<'protractor/built/frameworks/debugprint'>;
}
declare module 'protractor/built/frameworks/explorer.js' {
  declare module.exports: $Exports<'protractor/built/frameworks/explorer'>;
}
declare module 'protractor/built/frameworks/jasmine.js' {
  declare module.exports: $Exports<'protractor/built/frameworks/jasmine'>;
}
declare module 'protractor/built/frameworks/mocha.js' {
  declare module.exports: $Exports<'protractor/built/frameworks/mocha'>;
}
declare module 'protractor/built/frameworks/setupAfterEach.js' {
  declare module.exports: $Exports<'protractor/built/frameworks/setupAfterEach'>;
}
declare module 'protractor/built/index.js' {
  declare module.exports: $Exports<'protractor/built/index'>;
}
declare module 'protractor/built/launcher.js' {
  declare module.exports: $Exports<'protractor/built/launcher'>;
}
declare module 'protractor/built/locators.js' {
  declare module.exports: $Exports<'protractor/built/locators'>;
}
declare module 'protractor/built/logger.js' {
  declare module.exports: $Exports<'protractor/built/logger'>;
}
declare module 'protractor/built/plugins.js' {
  declare module.exports: $Exports<'protractor/built/plugins'>;
}
declare module 'protractor/built/ptor.js' {
  declare module.exports: $Exports<'protractor/built/ptor'>;
}
declare module 'protractor/built/runner.js' {
  declare module.exports: $Exports<'protractor/built/runner'>;
}
declare module 'protractor/built/runnerCli.js' {
  declare module.exports: $Exports<'protractor/built/runnerCli'>;
}
declare module 'protractor/built/selenium-webdriver/locators.js' {
  declare module.exports: $Exports<'protractor/built/selenium-webdriver/locators'>;
}
declare module 'protractor/built/selenium-webdriver/webdriver.js' {
  declare module.exports: $Exports<'protractor/built/selenium-webdriver/webdriver'>;
}
declare module 'protractor/built/taskLogger.js' {
  declare module.exports: $Exports<'protractor/built/taskLogger'>;
}
declare module 'protractor/built/taskRunner.js' {
  declare module.exports: $Exports<'protractor/built/taskRunner'>;
}
declare module 'protractor/built/taskScheduler.js' {
  declare module.exports: $Exports<'protractor/built/taskScheduler'>;
}
declare module 'protractor/built/util.js' {
  declare module.exports: $Exports<'protractor/built/util'>;
}
declare module 'protractor/built/webdriver-js-extender/index.js' {
  declare module.exports: $Exports<'protractor/built/webdriver-js-extender/index'>;
}
declare module 'protractor/example/conf.js' {
  declare module.exports: $Exports<'protractor/example/conf'>;
}
declare module 'protractor/example/example_spec.js' {
  declare module.exports: $Exports<'protractor/example/example_spec'>;
}
declare module 'protractor/gulpfile.js' {
  declare module.exports: $Exports<'protractor/gulpfile'>;
}
