// flow-typed signature: 16b0a70dd351b489ddbb6e4d394de699
// flow-typed version: <<STUB>>/react-google-charts_v^1.2.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-charts/__tests__/Chart.test' {
  declare module.exports: any;
}

declare module 'react-google-charts/__tests__/SmokeTest.test' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/dist/demo.8be77703' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/dist/demo.bde142b4' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/dist/demo.c8e2fecc' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/dist/manifest.d41d8cd9' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/src/components/ChartEditor' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/src/components/Menu' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/src/components/PageLayout' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/src/components/Usage' {
  declare module.exports: any;
}

declare module 'react-google-charts/demo/src/index' {
  declare module.exports: any;
}

declare module 'react-google-charts/es/components/Chart' {
  declare module.exports: any;
}

declare module 'react-google-charts/es/components/GoogleChartLoader' {
  declare module.exports: any;
}

declare module 'react-google-charts/es/components/PropsEditor' {
  declare module.exports: any;
}

declare module 'react-google-charts/es/constants/DEFAULT_CHART_COLORS' {
  declare module.exports: any;
}

declare module 'react-google-charts/es/constants/SAMPLE_DATA' {
  declare module.exports: any;
}

declare module 'react-google-charts/es/index' {
  declare module.exports: any;
}

declare module 'react-google-charts/example/src/App' {
  declare module.exports: any;
}

declare module 'react-google-charts/example/src/App.test' {
  declare module.exports: any;
}

declare module 'react-google-charts/example/src/index' {
  declare module.exports: any;
}

declare module 'react-google-charts/gulpfile' {
  declare module.exports: any;
}

declare module 'react-google-charts/lib/components/Chart' {
  declare module.exports: any;
}

declare module 'react-google-charts/lib/components/GoogleChartLoader' {
  declare module.exports: any;
}

declare module 'react-google-charts/lib/components/PropsEditor' {
  declare module.exports: any;
}

declare module 'react-google-charts/lib/constants/DEFAULT_CHART_COLORS' {
  declare module.exports: any;
}

declare module 'react-google-charts/lib/constants/SAMPLE_DATA' {
  declare module.exports: any;
}

declare module 'react-google-charts/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-charts/nwb.config' {
  declare module.exports: any;
}

declare module 'react-google-charts/src/components/Chart' {
  declare module.exports: any;
}

declare module 'react-google-charts/src/components/GoogleChartLoader' {
  declare module.exports: any;
}

declare module 'react-google-charts/src/components/PropsEditor' {
  declare module.exports: any;
}

declare module 'react-google-charts/src/constants/DEFAULT_CHART_COLORS' {
  declare module.exports: any;
}

declare module 'react-google-charts/src/constants/SAMPLE_DATA' {
  declare module.exports: any;
}

declare module 'react-google-charts/src/index' {
  declare module.exports: any;
}

declare module 'react-google-charts/test' {
  declare module.exports: any;
}

declare module 'react-google-charts/tests/index-test' {
  declare module.exports: any;
}

declare module 'react-google-charts/umd/react-google-charts' {
  declare module.exports: any;
}

declare module 'react-google-charts/umd/react-google-charts.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-charts/__tests__/Chart.test.js' {
  declare module.exports: $Exports<'react-google-charts/__tests__/Chart.test'>;
}
declare module 'react-google-charts/__tests__/SmokeTest.test.js' {
  declare module.exports: $Exports<'react-google-charts/__tests__/SmokeTest.test'>;
}
declare module 'react-google-charts/demo/dist/demo.8be77703.js' {
  declare module.exports: $Exports<'react-google-charts/demo/dist/demo.8be77703'>;
}
declare module 'react-google-charts/demo/dist/demo.bde142b4.js' {
  declare module.exports: $Exports<'react-google-charts/demo/dist/demo.bde142b4'>;
}
declare module 'react-google-charts/demo/dist/demo.c8e2fecc.js' {
  declare module.exports: $Exports<'react-google-charts/demo/dist/demo.c8e2fecc'>;
}
declare module 'react-google-charts/demo/dist/manifest.d41d8cd9.js' {
  declare module.exports: $Exports<'react-google-charts/demo/dist/manifest.d41d8cd9'>;
}
declare module 'react-google-charts/demo/src/components/ChartEditor.js' {
  declare module.exports: $Exports<'react-google-charts/demo/src/components/ChartEditor'>;
}
declare module 'react-google-charts/demo/src/components/Menu.js' {
  declare module.exports: $Exports<'react-google-charts/demo/src/components/Menu'>;
}
declare module 'react-google-charts/demo/src/components/PageLayout.js' {
  declare module.exports: $Exports<'react-google-charts/demo/src/components/PageLayout'>;
}
declare module 'react-google-charts/demo/src/components/Usage.js' {
  declare module.exports: $Exports<'react-google-charts/demo/src/components/Usage'>;
}
declare module 'react-google-charts/demo/src/index.js' {
  declare module.exports: $Exports<'react-google-charts/demo/src/index'>;
}
declare module 'react-google-charts/es/components/Chart.js' {
  declare module.exports: $Exports<'react-google-charts/es/components/Chart'>;
}
declare module 'react-google-charts/es/components/GoogleChartLoader.js' {
  declare module.exports: $Exports<'react-google-charts/es/components/GoogleChartLoader'>;
}
declare module 'react-google-charts/es/components/PropsEditor.js' {
  declare module.exports: $Exports<'react-google-charts/es/components/PropsEditor'>;
}
declare module 'react-google-charts/es/constants/DEFAULT_CHART_COLORS.js' {
  declare module.exports: $Exports<'react-google-charts/es/constants/DEFAULT_CHART_COLORS'>;
}
declare module 'react-google-charts/es/constants/SAMPLE_DATA.js' {
  declare module.exports: $Exports<'react-google-charts/es/constants/SAMPLE_DATA'>;
}
declare module 'react-google-charts/es/index.js' {
  declare module.exports: $Exports<'react-google-charts/es/index'>;
}
declare module 'react-google-charts/example/src/App.js' {
  declare module.exports: $Exports<'react-google-charts/example/src/App'>;
}
declare module 'react-google-charts/example/src/App.test.js' {
  declare module.exports: $Exports<'react-google-charts/example/src/App.test'>;
}
declare module 'react-google-charts/example/src/index.js' {
  declare module.exports: $Exports<'react-google-charts/example/src/index'>;
}
declare module 'react-google-charts/gulpfile.js' {
  declare module.exports: $Exports<'react-google-charts/gulpfile'>;
}
declare module 'react-google-charts/index' {
  declare module.exports: $Exports<'react-google-charts'>;
}
declare module 'react-google-charts/index.js' {
  declare module.exports: $Exports<'react-google-charts'>;
}
declare module 'react-google-charts/lib/components/Chart.js' {
  declare module.exports: $Exports<'react-google-charts/lib/components/Chart'>;
}
declare module 'react-google-charts/lib/components/GoogleChartLoader.js' {
  declare module.exports: $Exports<'react-google-charts/lib/components/GoogleChartLoader'>;
}
declare module 'react-google-charts/lib/components/PropsEditor.js' {
  declare module.exports: $Exports<'react-google-charts/lib/components/PropsEditor'>;
}
declare module 'react-google-charts/lib/constants/DEFAULT_CHART_COLORS.js' {
  declare module.exports: $Exports<'react-google-charts/lib/constants/DEFAULT_CHART_COLORS'>;
}
declare module 'react-google-charts/lib/constants/SAMPLE_DATA.js' {
  declare module.exports: $Exports<'react-google-charts/lib/constants/SAMPLE_DATA'>;
}
declare module 'react-google-charts/lib/index.js' {
  declare module.exports: $Exports<'react-google-charts/lib/index'>;
}
declare module 'react-google-charts/nwb.config.js' {
  declare module.exports: $Exports<'react-google-charts/nwb.config'>;
}
declare module 'react-google-charts/src/components/Chart.js' {
  declare module.exports: $Exports<'react-google-charts/src/components/Chart'>;
}
declare module 'react-google-charts/src/components/GoogleChartLoader.js' {
  declare module.exports: $Exports<'react-google-charts/src/components/GoogleChartLoader'>;
}
declare module 'react-google-charts/src/components/PropsEditor.js' {
  declare module.exports: $Exports<'react-google-charts/src/components/PropsEditor'>;
}
declare module 'react-google-charts/src/constants/DEFAULT_CHART_COLORS.js' {
  declare module.exports: $Exports<'react-google-charts/src/constants/DEFAULT_CHART_COLORS'>;
}
declare module 'react-google-charts/src/constants/SAMPLE_DATA.js' {
  declare module.exports: $Exports<'react-google-charts/src/constants/SAMPLE_DATA'>;
}
declare module 'react-google-charts/src/index.js' {
  declare module.exports: $Exports<'react-google-charts/src/index'>;
}
declare module 'react-google-charts/test.js' {
  declare module.exports: $Exports<'react-google-charts/test'>;
}
declare module 'react-google-charts/tests/index-test.js' {
  declare module.exports: $Exports<'react-google-charts/tests/index-test'>;
}
declare module 'react-google-charts/umd/react-google-charts.js' {
  declare module.exports: $Exports<'react-google-charts/umd/react-google-charts'>;
}
declare module 'react-google-charts/umd/react-google-charts.min.js' {
  declare module.exports: $Exports<'react-google-charts/umd/react-google-charts.min'>;
}
