// flow-typed signature: 8d3e890c52ed6dbd0ba63bb887f8af03
// flow-typed version: <<STUB>>/react-number-format_v^0.1.3/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-number-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-number-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-number-format/dist/react-number-format' {
  declare module.exports: any;
}

declare module 'react-number-format/dist/react-number-format.min' {
  declare module.exports: any;
}

declare module 'react-number-format/example/src/index' {
  declare module.exports: any;
}

declare module 'react-number-format/karma.conf' {
  declare module.exports: any;
}

declare module 'react-number-format/lib/number_format' {
  declare module.exports: any;
}

declare module 'react-number-format/src/number_format' {
  declare module.exports: any;
}

declare module 'react-number-format/test/input_test' {
  declare module.exports: any;
}

declare module 'react-number-format/webpack.bundle.config' {
  declare module.exports: any;
}

declare module 'react-number-format/webpack.dev.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-number-format/dist/react-number-format.js' {
  declare module.exports: $Exports<'react-number-format/dist/react-number-format'>;
}
declare module 'react-number-format/dist/react-number-format.min.js' {
  declare module.exports: $Exports<'react-number-format/dist/react-number-format.min'>;
}
declare module 'react-number-format/example/src/index.js' {
  declare module.exports: $Exports<'react-number-format/example/src/index'>;
}
declare module 'react-number-format/karma.conf.js' {
  declare module.exports: $Exports<'react-number-format/karma.conf'>;
}
declare module 'react-number-format/lib/number_format.js' {
  declare module.exports: $Exports<'react-number-format/lib/number_format'>;
}
declare module 'react-number-format/src/number_format.js' {
  declare module.exports: $Exports<'react-number-format/src/number_format'>;
}
declare module 'react-number-format/test/input_test.js' {
  declare module.exports: $Exports<'react-number-format/test/input_test'>;
}
declare module 'react-number-format/webpack.bundle.config.js' {
  declare module.exports: $Exports<'react-number-format/webpack.bundle.config'>;
}
declare module 'react-number-format/webpack.dev.config.js' {
  declare module.exports: $Exports<'react-number-format/webpack.dev.config'>;
}
