// flow-typed signature: d84a793ab525f600dd47286fbd48f331
// flow-typed version: <<STUB>>/react-chartjs-2_v^1.6.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-chartjs-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-chartjs-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-chartjs-2/dist/react-chartjs-2' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/dist/react-chartjs-2.min' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/example/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/example/dist/common' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/example/dist/example' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/gulpfile' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/lib/index' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/test/__tests__/Chart_spec' {
  declare module.exports: any;
}

declare module 'react-chartjs-2/test/config/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-chartjs-2/dist/react-chartjs-2.js' {
  declare module.exports: $Exports<'react-chartjs-2/dist/react-chartjs-2'>;
}
declare module 'react-chartjs-2/dist/react-chartjs-2.min.js' {
  declare module.exports: $Exports<'react-chartjs-2/dist/react-chartjs-2.min'>;
}
declare module 'react-chartjs-2/example/dist/bundle.js' {
  declare module.exports: $Exports<'react-chartjs-2/example/dist/bundle'>;
}
declare module 'react-chartjs-2/example/dist/common.js' {
  declare module.exports: $Exports<'react-chartjs-2/example/dist/common'>;
}
declare module 'react-chartjs-2/example/dist/example.js' {
  declare module.exports: $Exports<'react-chartjs-2/example/dist/example'>;
}
declare module 'react-chartjs-2/gulpfile.js' {
  declare module.exports: $Exports<'react-chartjs-2/gulpfile'>;
}
declare module 'react-chartjs-2/lib/index.js' {
  declare module.exports: $Exports<'react-chartjs-2/lib/index'>;
}
declare module 'react-chartjs-2/test/__tests__/Chart_spec.js' {
  declare module.exports: $Exports<'react-chartjs-2/test/__tests__/Chart_spec'>;
}
declare module 'react-chartjs-2/test/config/setup.js' {
  declare module.exports: $Exports<'react-chartjs-2/test/config/setup'>;
}
