// flow-typed signature: ccdb4439f279915c19029fefd9a68f61
// flow-typed version: <<STUB>>/react-moment_v^0.2.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-moment/dist/index' {
  declare module.exports: any;
}

declare module 'react-moment/src/index' {
  declare module.exports: any;
}

declare module 'react-moment/tests/index' {
  declare module.exports: any;
}

declare module 'react-moment/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-moment/dist/index.js' {
  declare module.exports: $Exports<'react-moment/dist/index'>;
}
declare module 'react-moment/src/index.js' {
  declare module.exports: $Exports<'react-moment/src/index'>;
}
declare module 'react-moment/tests/index.js' {
  declare module.exports: $Exports<'react-moment/tests/index'>;
}
declare module 'react-moment/webpack.config.js' {
  declare module.exports: $Exports<'react-moment/webpack.config'>;
}
