// flow-typed signature: 34f8ef6ecf5aa02749e019cd920dec59
// flow-typed version: <<STUB>>/react-moment_v0.0.3/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-moment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-moment/dist/index' {
  declare module.exports: any;
}

declare module 'react-moment/src/index' {
  declare module.exports: any;
}

declare module 'react-moment/tests/index' {
  declare module.exports: any;
}

declare module 'react-moment/webpack.config' {
  declare module.exports: any;
}

declare module 'react-moment/webpack.serve' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-moment/dist/index.js' {
  declare module.exports: $Exports<'react-moment/dist/index'>;
}
declare module 'react-moment/src/index.js' {
  declare module.exports: $Exports<'react-moment/src/index'>;
}
declare module 'react-moment/tests/index.js' {
  declare module.exports: $Exports<'react-moment/tests/index'>;
}
declare module 'react-moment/webpack.config.js' {
  declare module.exports: $Exports<'react-moment/webpack.config'>;
}
declare module 'react-moment/webpack.serve.js' {
  declare module.exports: $Exports<'react-moment/webpack.serve'>;
}
