// flow-typed signature: 6168efeabd6a116615ace4602290389c
// flow-typed version: <<STUB>>/serve-static_v^1.11.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serve-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'serve-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'serve-static/index' {
  declare module.exports: $Exports<'serve-static'>;
}
declare module 'serve-static/index.js' {
  declare module.exports: $Exports<'serve-static'>;
}
